#Open required libraries
library(reshape2)
library(ggplot2)
library(ggpubr)

#Make sure that there is no open graphs
graphics.off()

size = 24

#Plots of sensitivity analysis
results<-read.table("../results/sensitivity_analysis.dat", header=T)

p1<-ggplot(results, aes(x=diff, y=TCP_0,fill=factor(mu)))+geom_bar(position='dodge', stat = "identity")+scale_fill_manual(values=c("blue", "red"), labels=c(expression(mu~"= 0.027 h"^-1), expression(mu~"= 0.5 h"^-1)))+xlab("Parameter change (%)")+ylab("Mean TCP relative change (%)")+theme_bw(base_size=size)+theme(strip.background = element_rect(colour="black", fill="white"),legend.title=element_blank(),legend.box.background=element_rect(linewidth = 1.5), legend.direction="vertical",strip.text.x = element_text(size = size))+facet_grid(cols=vars("alpha[37]"),labeller = label_parsed)+ theme(legend.position = "none")+scale_x_discrete(limit=c("1","2","3","4","5","6","7","8","9","10","11","12","13","14"),breaks=c("1","2","3","4","5","6","7","8","9","10","11","12","13","14"), labels=c("-25","-20","-15","-10","-5","-3","-1","1","3","5","10","15","20","25"))
p2<-ggplot(results, aes(x=diff, y=TCP_1,fill=factor(mu)))+geom_bar(position='dodge', stat = "identity")+scale_fill_manual(values=c("blue", "red"), labels=c(expression(mu~"= 0.027 h"^-1), expression(mu~"= 0.5 h"^-1)))+xlab("Parameter change (%)")+ylab("Mean TCP relative change (%)")+theme_bw(base_size=size)+theme(strip.background = element_rect(colour="black", fill="white"),legend.title=element_blank(),legend.box.background=element_rect(linewidth = 1.5), legend.direction="vertical",strip.text.x = element_text(size = size))+facet_grid(cols=vars("alpha[41]"),labeller = label_parsed)+ theme(legend.position = "none")+scale_x_discrete(limit=c("1","2","3","4","5","6","7","8","9","10","11","12","13","14"),breaks=c("1","2","3","4","5","6","7","8","9","10","11","12","13","14"), labels=c("-25","-20","-15","-10","-5","-3","-1","1","3","5","10","15","20","25"))+coord_cartesian(ylim=c(0,16))
p3<-ggplot(results, aes(x=diff, y=TCP_2,fill=factor(mu)))+geom_bar(position='dodge', stat = "identity")+scale_fill_manual(values=c("blue", "red"), labels=c(expression(mu~"= 0.027 h"^-1), expression(mu~"= 0.5 h"^-1)))+xlab("Parameter change (%)")+ylab("Mean TCP relative change (%)")+theme_bw(base_size=size)+theme(strip.background = element_rect(colour="black", fill="white"),legend.title=element_blank(),legend.box.background=element_rect(linewidth = 1.5), legend.direction="vertical",strip.text.x = element_text(size = size))+facet_grid(cols=vars("beta[37]"),labeller = label_parsed)+ theme(legend.position = "none")+scale_x_discrete(limit=c("1","2","3","4","5","6","7","8","9","10","11","12","13","14"),breaks=c("1","2","3","4","5","6","7","8","9","10","11","12","13","14"), labels=c("-25","-20","-15","-10","-5","-3","-1","1","3","5","10","15","20","25"))+coord_cartesian(ylim=c(0,16))
p4<-ggplot(results, aes(x=diff, y=TCP_3,fill=factor(mu)))+geom_bar(position='dodge', stat = "identity")+scale_fill_manual(values=c("blue", "red"), labels=c(expression(mu~"= 0.027 h"^-1), expression(mu~"= 0.5 h"^-1)))+xlab("Parameter change (%)")+ylab("Mean TCP relative change (%)")+theme_bw(base_size=size)+theme(strip.background = element_rect(colour="black", fill="white"),legend.title=element_blank(),legend.box.background=element_rect(linewidth = 1.5), legend.direction="vertical",strip.text.x = element_text(size = size))+facet_grid(cols=vars("beta[41]"),labeller = label_parsed)+ theme(legend.position = "none")+scale_x_discrete(limit=c("1","2","3","4","5","6","7","8","9","10","11","12","13","14"),breaks=c("1","2","3","4","5","6","7","8","9","10","11","12","13","14"), labels=c("-25","-20","-15","-10","-5","-3","-1","1","3","5","10","15","20","25"))+coord_cartesian(ylim=c(0,16))
p5<-ggplot(results, aes(x=diff, y=TCP_4,fill=factor(mu)))+geom_bar(position='dodge', stat = "identity")+scale_fill_manual(values=c("blue", "red"), labels=c(expression(mu~"= 0.027 h"^-1), expression(mu~"= 0.5 h"^-1)))+xlab("Parameter change (%)")+ylab("Mean TCP relative change (%)")+theme_bw(base_size=size)+theme(strip.background = element_rect(colour="black", fill="white"),legend.title=element_blank(),legend.box.background=element_rect(linewidth = 1.5), legend.direction="vertical",strip.text.x = element_text(size = size))+facet_grid(cols=vars("mu"),labeller = label_parsed)+ theme(legend.position = "none")+scale_x_discrete(limit=c("1","2","3","4","5","6","7","8","9","10","11","12","13","14"),breaks=c("1","2","3","4","5","6","7","8","9","10","11","12","13","14"), labels=c("-25","-20","-15","-10","-5","-3","-1","1","3","5","10","15","20","25"))+coord_cartesian(ylim=c(0,16))
p6<-ggplot(results, aes(x=diff, y=TCP_5,fill=factor(mu)))+geom_bar(position='dodge', stat = "identity")+scale_fill_manual(values=c("blue", "red"), labels=c(expression(mu~"= 0.027 h"^-1), expression(mu~"= 0.5 h"^-1)))+xlab("Parameter change (%)")+ylab("Mean TCP relative change (%)")+theme_bw(base_size=size)+theme(strip.background = element_rect(colour="black", fill="white"),legend.title=element_blank(),legend.box.background=element_rect(linewidth = 1.5), legend.direction="vertical",strip.text.x = element_text(size = size))+facet_grid(cols=vars('Delta*S'),labeller = label_parsed)+ theme(legend.position = "none")+scale_x_discrete(limit=c("1","2","3","4","5","6","7","8","9","10","11","12","13","14"),breaks=c("1","2","3","4","5","6","7","8","9","10","11","12","13","14"), labels=c("-25","-20","-15","-10","-5","-3","-1","1","3","5","10","15","20","25"))+coord_cartesian(ylim=c(0,16))


legend<-ggplot(results, aes(x=diff, y=TCP_5,fill=factor(mu)))+geom_bar(position='dodge', stat = "identity")+scale_fill_manual(values=c("blue", "red"), labels=c(expression(mu~"= 0.027 h"^-1), expression(mu~"= 0.5 h"^-1)))+xlab("")+ylab("")+coord_cartesian(xlim=c(0,0),ylim=c(0,0))+theme_void()+theme(legend.text=element_text(size=size),legend.title=element_blank(),legend.box.background=element_rect(linewidth = 1.), legend.direction="horizontal", legend.position = c(0.5,0.5),legend.margin=margin(2,5,2,-1, unit='mm'),legend.spacing.x = unit(0.5, 'cm'))+scale_x_discrete(expand = c(0,0))+scale_y_discrete(expand = c(0,0))

pdf("Figure_12.pdf",width=24,height=14)
ggarrange(ggarrange(p1+xlab(NULL), p2+xlab(NULL), p3+xlab(NULL), p4, p5, p6, font.label = list(size = size),ncol = 3, nrow = 2),legend, heights = c(2, 0.1), nrow = 2)
graphics.off()