#Open required libraries
library(reshape2)
library(ggplot2)
library(ggpubr)

#Make sure that there is no open graphs
graphics.off()

size = 24

#Plots of random
results<-read.table("../results/TCP_random.dat", header=T)

p1<-ggplot(results, aes(x=Temp, y=TCP, color=factor(N_HT)))+geom_point()+scale_color_manual(values=c("blue", "darkgreen", "orange", "red"), labels=c("3 HT sessions", "4 HT sessions", "5 HT sessions", "6 HT sessions"))+xlab("Temperature (°C)")+ylab("TCP")+theme_bw(base_size=size)+theme(strip.background = element_rect(colour="black", fill="white"),legend.title=element_blank(),legend.box.background=element_rect(linewidth = 1.5),legend.position=c(0.2,0.22), legend.direction="vertical",legend.margin=margin(1,1,1,0, unit='mm'),legend.spacing.x=unit(0, "mm"),legend.spacing.y=unit(0, "mm"))+facet_grid(cols=vars("Mean~Temperature"),labeller = label_parsed)+xlim(39,43)+ylim(.55,1.)+geom_hline(yintercept=0.5533459312634031, linewidth=1.5)+annotate("text", x=42.7, y=0.58, label="Only RT", size=8)
p2<-ggplot(results, aes(x=interval, y=TCP, color=factor(N_HT)))+geom_point()+scale_color_manual(values=c("blue", "darkgreen", "orange", "red"), labels=c("3 HT sessions", "4 HT sessions", "5 HT sessions", "6 HT sessions"))+xlab("Time interval (min)")+ylab("TCP")+theme_bw(base_size=size)+theme(strip.background = element_rect(colour="black", fill="white"),legend.title=element_blank(),legend.box.background=element_rect(linewidth = 1.5),legend.position=c(0.2,0.22), legend.direction="vertical",legend.margin=margin(1,1,1,0, unit='mm'),legend.spacing.x=unit(0, "mm"),legend.spacing.y=unit(0, "mm"))+facet_grid(cols=vars("Mean~Time~Interval"),rows=vars("Without~direct~killing"),labeller = label_parsed)+scale_x_continuous(limits=c(10,240),breaks=c(10,50,100,150,200,240))+ylim(.55,1.)+geom_hline(yintercept=0.5533459312634031, linewidth=1.5)+annotate("text", x=220, y=0.58, label="Only RT", size=8)
p3<-ggplot(results, aes(x=Temp, y=TCP_kill, color=factor(N_HT)))+geom_point()+scale_color_manual(values=c("blue", "darkgreen", "orange", "red"), labels=c("3 HT sessions", "4 HT sessions", "5 HT sessions", "6 HT sessions"))+xlab("Temperature (°C)")+ylab("TCP")+theme_bw(base_size=size)+theme(strip.background = element_rect(colour="black", fill="white"),legend.title=element_blank(),legend.box.background=element_rect(linewidth = 1.5),legend.position=c(0.17,0.2), legend.direction="vertical",legend.margin=margin(1,1,1,0, unit='mm'),legend.spacing.x=unit(0, "mm"),legend.spacing.y=unit(0, "mm"))+facet_grid(labeller = label_parsed)+xlim(39,43)+ylim(.55,1.)+geom_hline(yintercept=0.5533459312634031, linewidth=1.5)+annotate("text", x=42.7, y=0.58, label="Only RT", size=8)
p4<-ggplot(results, aes(x=interval, y=TCP_kill, color=factor(N_HT)))+geom_point()+scale_color_manual(values=c("blue", "darkgreen", "orange", "red"), labels=c("3 HT sessions", "4 HT sessions", "5 HT sessions", "6 HT sessions"))+xlab("Time interval (min)")+ylab("TCP")+theme_bw(base_size=size)+theme(strip.background = element_rect(colour="black", fill="white"),legend.title=element_blank(),legend.box.background=element_rect(linewidth = 1.5),legend.position=c(0.2,0.2), legend.direction="vertical",legend.margin=margin(1,1,1,0, unit='mm'),legend.spacing.x=unit(0, "mm"),legend.spacing.y=unit(0, "mm"))+facet_grid(rows=vars("With~direct~killing"),labeller = label_parsed)+scale_x_continuous(limits=c(10,240),breaks=c(10,50,100,150,200,240))+ylim(.55,1.)+geom_hline(yintercept=0.5533459312634031, linewidth=1.5)+annotate("text", x=220, y=0.58, label="Only RT", size=8)


pdf("Figure_7.pdf",width=16,height=12)
ggarrange(p1+ xlab(""), p2 + xlab(""), p3, p4, font.label = list(size = size),ncol = 2, nrow = 2)
graphics.off()

p1<-ggplot(results, aes(x=Temp, y=TCP_high, color=factor(N_HT)))+geom_point()+scale_color_manual(values=c("blue", "darkgreen", "orange", "red"), labels=c("3 sessions", "4 sessions", "5 sessions", "6 sessions"))+xlab("Temperature (°C)")+ylab("TCP")+theme_bw(base_size=size)+theme(strip.background = element_rect(colour="black", fill="white"),legend.title=element_blank(),legend.box.background=element_rect(linewidth = 1.5),legend.position=c(0.17,0.8), legend.direction="vertical",legend.margin=margin(1,1,1,0, unit='mm'),legend.spacing.x=unit(0, "mm"),legend.spacing.y=unit(0, "mm"))+facet_grid(cols=vars("Mean~Temperature"),labeller = label_parsed)+xlim(39,43)+ylim(.55,1.)+geom_hline(yintercept=0.5533459312634031, linewidth=1.5)+annotate("text", x=42.7, y=0.58, label="Only RT", size=8)
p2<-ggplot(results, aes(x=interval, y=TCP_high, color=factor(N_HT)))+geom_point()+scale_color_manual(values=c("blue", "darkgreen", "orange", "red"), labels=c("3 sessions", "4 sessions", "5 sessions", "6 sessions"))+xlab("Time interval (min)")+ylab("TCP")+theme_bw(base_size=size)+theme(strip.background = element_rect(colour="black", fill="white"),legend.title=element_blank(),legend.box.background=element_rect(linewidth = 1.5),legend.position=c(0.17,0.2), legend.direction="vertical",legend.margin=margin(1,1,1,0, unit='mm'),legend.spacing.x=unit(0, "mm"),legend.spacing.y=unit(0, "mm"))+facet_grid(cols=vars("Mean~Time~Interval"),rows=vars("Without~direct~killing"),labeller = label_parsed)+scale_x_continuous(limits=c(10,240),breaks=c(10,50,100,150,200,240))+ylim(.55,1.)+geom_hline(yintercept=0.5533459312634031, linewidth=1.5)+annotate("text", x=220, y=0.58, label="Only RT", size=8)
p3<-ggplot(results, aes(x=Temp, y=TCP_kill_high, color=factor(N_HT)))+geom_point()+scale_color_manual(values=c("blue", "darkgreen", "orange", "red"), labels=c("3 sessions", "4 sessions", "5 sessions", "6 sessions"))+xlab("Temperature (°C)")+ylab("TCP")+theme_bw(base_size=size)+theme(strip.background = element_rect(colour="black", fill="white"),legend.title=element_blank(),legend.box.background=element_rect(linewidth = 1.5),legend.position=c(0.86,0.3), legend.direction="vertical",legend.margin=margin(1,1,1,0, unit='mm'),legend.spacing.x=unit(0, "mm"),legend.spacing.y=unit(0, "mm"))+facet_grid(labeller = label_parsed)+xlim(39,43)+ylim(.55,1.)+geom_hline(yintercept=0.5533459312634031, linewidth=1.5)+annotate("text", x=42.7, y=0.58, label="Only RT", size=8)
p4<-ggplot(results, aes(x=interval, y=TCP_kill_high, color=factor(N_HT)))+geom_point()+scale_color_manual(values=c("blue", "darkgreen", "orange", "red"), labels=c("3 sessions", "4 sessions", "5 sessions", "6 sessions"))+xlab("Time interval (min)")+ylab("TCP")+theme_bw(base_size=size)+theme(strip.background = element_rect(colour="black", fill="white"),legend.title=element_blank(),legend.box.background=element_rect(linewidth = 1.5),legend.position=c(0.17,0.2), legend.direction="vertical",legend.margin=margin(1,1,1,0, unit='mm'),legend.spacing.x=unit(0, "mm"),legend.spacing.y=unit(0, "mm"))+facet_grid(rows=vars("With~direct~killing"),labeller = label_parsed)+scale_x_continuous(limits=c(10,240),breaks=c(10,50,100,150,200,240))+ylim(.55,1.)+geom_hline(yintercept=0.5533459312634031, linewidth=1.5)+annotate("text", x=220, y=0.58, label="Only RT", size=8)


pdf("Figure_8.pdf",width=16,height=12)
ggarrange(p1+ xlab(""), p2 + xlab(""), p3, p4, font.label = list(size = size),ncol = 2, nrow = 2)
graphics.off()